name: pore-c-snakemake
channels:
- defaults
dependencies:
- pandas ==1.*,>=1.0.5
- python-box ==4.*,>=4.2.3
- defopt ==6.*,>=6.0.0
- dephell ==0.*,>=0.8.3
- gitpython ==3.*,>=3.1.3
- invoke ==1.*,>=1.4.1
- pre-commit ==2.*,>=2.5.1
- snakefmt ==0.*,>=0.1.1
- snakemake ==5.*,>=5.19.3
- tabulate ==0.*,>=0.8.7
